it_solutions_cars/api/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter


from .views import CarViewSet, CommentViewSet

router = DefaultRouter()

router.register(r'cars', CarViewSet)
router.register(r'cars/(?P<car_pk>\d+)/comments', CommentViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('', include('djoser.urls')),
    path('', include('djoser.urls.jwt')),
]

app_name = 'api'

it_solutions_cars/cars/urls.py
from django.urls import path
from .views import CarIndexView, CarCreateView, CarDetailView, CarUpdateView, CommentCreateView, CarDeleteView

urlpatterns = [
    path('', CarIndexView.as_view(), name='index'),
    path('cars/new', CarCreateView.as_view(), name='create'),
    path('cars/<int:pk>', CarDetailView.as_view(), name='detail'),
    path('cars/<int:pk>/update', CarUpdateView.as_view(), name='update'),
    path('cars/<int:pk>/add_comment', CommentCreateView.as_view(), name='add_comment'),
    path('cars/<int:pk>/delete', CarDeleteView.as_view(), name='delete'),
]

app_name = 'cars'

it_solutions_cars/it_solutions_cars/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularRedocView, SpectacularAPIView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls', namespace='cars')),
    path('auth/', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

it_solutions_cars/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from .views import SignUpView, CustomLoginView


app_name = 'users'

urlpatterns = [

    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

it_solutions_cars/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Автомобили{% endblock %}</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container mt-5">
        {% block content %}
        {% endblock %}
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

it_solutions_cars/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'cars:index' %}">Автомобили</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars:create' %}">Создать</a>
                </li>
                <li class="nav-item">
                    <form id="logout-form" action="{% url 'users:logout' %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link nav-link text-danger">Выйти</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:signup' %}">Зарегистрироваться</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>